TEXT={
 'handoff':{'es':'Te paso con Bernat para que revise tu consulta. El asistente y los seguimientos quedan pausados mientras te atiende.','en':'I will pass your enquiry to Bernat. The assistant and follow-ups are paused while he reviews it.','hu':'Átadom a kérdésedet Bernatnak. Az asszisztens és az automatikus üzenetek szünetelnek, amíg ő foglalkozik veled.'},
 'followup':{'es':'Hola, soy el asistente virtual de Scorus Team. ¿Te queda alguna duda sobre el programa o quieres organizar tu valoración con Bernat?','en':'Hello, I am the Scorus Team virtual assistant. Do you have any questions about the programme, or would you like to arrange your assessment with Bernat?','hu':'Szia, a Scorus Team virtuális asszisztense vagyok. Van kérdésed a programról, vagy szeretnél időpontot egyeztetni Bernattal?'},
 'paid':{'es':'Pago confirmado. Tu plaza está reservada. Prepararemos el acceso a Scorus App y el cuestionario inicial. Bernat revisará tus datos antes de activar el plan; a partir de esa activación empezará tu programa.','en':'Payment confirmed; your place is reserved. We will arrange your Scorus App access and initial questionnaire. Bernat will review your information before activating your plan. Your programme starts on that activation date.','hu':'A fizetés visszaigazolva, a helyed lefoglalva. Előkészítjük a Scorus App hozzáférést és a kezdeti kérdőívet. Bernat átnézi az adataidat a terv aktiválása előtt. A program időtartama az aktiválástól kezdődik.'},
 'active':{'es':'Bernat ha confirmado que tu plan ya está activo en Scorus App. La duración de tu programa empieza hoy.','en':'Bernat has confirmed that your plan is active in Scorus App. Your programme starts today.','hu':'Bernat megerősítette, hogy a terved aktív a Scorus Appban. A program időtartama ma kezdődik.'},
 'renewal':{'es':'Tu programa termina en {days} días. La renovación es manual: si quieres continuar, podemos organizar la revisión con Bernat. No se iniciará otro periodo por silencio.','en':'Your programme ends in {days} days. Renewal requires your agreement. If you would like to continue, we can arrange a review with Bernat. No new term starts automatically.','hu':'A programod {days} nap múlva véget ér. A megújításhoz külön beleegyezés szükséges. Ha folytatnád, egyeztethetünk Bernattal. Nem indul automatikusan új időszak.'}
}
def text(key,lead,**values):
    return TEXT[key].get(lead.language,TEXT[key]['es']).format(**values)
