TEXT={
 'handoff':{'es':'Te paso con Bernat para que revise tu consulta. El asistente y los seguimientos quedan pausados mientras te atiende.','en':'I will pass your enquiry to Bernat. The assistant and follow-ups are paused while he reviews it.','hu':'Átadom a kérdésedet Bernatnak. Az asszisztens és az automatikus üzenetek szünetelnek, amíg ő foglalkozik veled.'},
 'followup':{'es':'¿Te queda alguna duda sobre el programa o cómo empezar? Puedo explicártelo por aquí.','en':'Do you have any questions about the programme or how to get started? I can help here.','hu':'Van még kérdésed a programról vagy a kezdésről? Itt segítek.'},
 'paid':{'es':'Pago confirmado. Tu plaza está reservada. Prepararemos el acceso a Scorus App y el cuestionario inicial. Bernat revisará tus datos antes de activar el plan; a partir de esa activación empezará tu programa.','en':'Payment confirmed; your place is reserved. We will arrange your Scorus App access and initial questionnaire. Bernat will review your information before activating your plan. Your programme starts on that activation date.','hu':'A fizetés visszaigazolva, a helyed lefoglalva. Előkészítjük a Scorus App hozzáférést és a kezdeti kérdőívet. Bernat átnézi az adataidat a terv aktiválása előtt. A program időtartama az aktiválástól kezdődik.'},
 'active':{'es':'Bernat ha confirmado que tu plan ya está activo en Scorus App. La duración de tu programa empieza hoy.','en':'Bernat has confirmed that your plan is active in Scorus App. Your programme starts today.','hu':'Bernat megerősítette, hogy a terved aktív a Scorus Appban. A program időtartama ma kezdődik.'},
 'renewal':{'es':'Tu programa termina en {days} días. Si quieres continuar, puedo explicarte las opciones y preparar la continuidad para cuando termine el periodo actual. Necesita una nueva aceptación expresa; no se renueva automáticamente.','en':'Your programme ends in {days} days. If you would like to continue, I can explain the options for after your current term. A new explicit agreement is required; renewal is never automatic.','hu':'A programod {days} nap múlva véget ér. Ha folytatnád, bemutatom a jelenlegi időszak utáni lehetőségeket. Új kifejezett elfogadás szükséges; nincs automatikus megújítás.'}
}
def text(key,lead,**values):
    return TEXT[key].get(lead.language,TEXT[key]['es']).format(**values)
